### ISSUE TITLE
[iOS] Badges do not show if initially set to blank

### ISSUE THREAD

**Issue by vtjon** [rhanb/nativescript-bottombar#68]
It appears that on iOS that the badge number does not show unless you initialize the item with a non-empty string. In looking at the iOS code, it appears that it only adds the badgeLabel to the view when it's not an empty string.

**Comment by rayneram** [comment]
Any news on when this might be fixed? As far as I can tell, the issue is actually in MiniTabBar rather than this plugin. Workaround is to initialise each item with non-empty string and then set them all back to empty strings in the bottombar loaded handler before they appear.

**Comment by rhanb** [comment]
Please provide code to reproduce the issue, thanks 👍

**Comment by marcuschoong** [comment]
#75 is related to this issue. if the badges is not initially at the first place(like the following example). when updating the notification will not display the badges on ios. 

> public bottomBarItems: Array<BottomBarItem> = [
>         new BottomBarItem(0, "Chat", "ic_home_black_24dp", "whitesmoke", new Notification("white", "red", "")),
>     ];

the badges will update if i declare the bottomBarItem like the following:
> public bottomBarItems: Array<BottomBarItem> = [
>         new BottomBarItem(0, "Chat", "ic_home_black_24dp", "whitesmoke", new Notification("white", "red", "0")),
>     ];

**Comment by rhanb** [comment]
Should be fixed with the pre-release 4.0.0-rc1.1. Be careful, there is a lot of breaking changes.

**Comment by marcuschoong** [comment]
package.json on the NativeScript still showing that the latest version is 3.0.8. how can I apply the changes ?

**Comment by rhanb** [comment]
Yes just follow the readme from the repo you should be good to go. It
doesn't show up because it's an RC release

Le mar. 12 mars 2019 à 7:42 AM, marcuschoong <notifications@github.com> a
écrit :

**Comment by marcuschoong** [comment]
the latest release doesn't fix this issue. its still need to set the initially badge to 0 in order to display the badge when increase to 1.

**Comment by rhanb** [comment]
Could you provide a repo or something to reproduce the issue ? Wich version are you using ? 

It should be fixed
